Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false